### ISSUE TITLE
Can't comment or like your blogs

### ISSUE THREAD

**Issue by Seandor** [FrontendSophie/old-blog#88]
Your blog site requires login to like/comment blogs, I clicked on "Login" and authorize to use github to login you blog, but the login part seems not working.

**Comment by FrontendSophie** [comment]
@Seandor This blog is already deprecated and no longer maintained. If you have some issues about comment section, please report to https://github.com/imsun/gitment  😃 Thanks la, long time no see uh~

**Comment by Seandor** [comment]
浓浓的新加坡味英语...
